# Generated by Django 4.2.3 on 2023-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('office_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
