# Generated by Django 4.2.3 on 2023-07-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0003_rename_name_teacher_姓名_rename_expertise_teacher_專長_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='聯絡方式',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='專長',
            new_name='expertise',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='姓名',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='辦公室位置',
            new_name='office_location',
        ),
    ]
