# Generated by Django 4.2.3 on 2023-07-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0004_rename_聯絡方式_teacher_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='teachers',
        ),
    ]
