# Generated by Django 4.2.3 on 2023-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0005_rename_teacher_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='office_location',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
