# Generated by Django 4.2.3 on 2023-07-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0006_rename_office_location_teachers_office_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
