# Generated by Django 4.2.3 on 2023-07-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0007_alter_teachers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='teacher',
        ),
    ]
