# Generated by Django 4.2.3 on 2023-07-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0008_alter_teachers_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='Teacher',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
