# Generated by Django 4.2.3 on 2023-07-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0009_rename_teachers_teacher_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='fjuqapp_teacher',
        ),
    ]
