# Generated by Django 4.2.2 on 2023-07-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjuqapp', '0010_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
